export const sentences: any[] = [
    {
        id: 1,
        firstSentence: 'これは',
        coloredSentence: '何ですか',
        lastSentence: '',
        meaning: 'Đây là cái gì',
        start: 4,
        end: 7,
        grammar: 'MĐ + 何ですか',
        description: 'Dùng để hỏi cái gì',
        highlightFlag: false,
        grammarFlag: false,
        meaningFlag: false,
    }, 
    {
        id: 2,
        firstSentence: 'あなたはどこへ',
        coloredSentence: '行こうとしますか',
        lastSentence: '、DNですか',
        meaning: 'Bạn dự định đi đâu',
        start: 8,
        end: 14,
        grammar: 'V-よう +　とします',
        description: 'Dự định làm gì đó',
        highlightFlag: false,
        grammarFlag: false,
        meaningFlag: false,
    }, 
]